#!/usr/bin/perl
use strict;

my @choices = ();
my $i = 0;
for (`pacmd list-sinks`) {
    if( /name:.*<(.+)>/) {
            $choices[$i++] = $1;
                    print "$i:\t$1\n";
                        }
                        }
                        my $choice = $choices[<>-1] or die "invalid choice";
                        exec (qw(pacmd load-module module-remap-sink sink_name=mono),
                            "master=$choice",
                                qw(channels=2 channel_map=mono,mono));
